"use strict";/* global jQuery */ /**
 * show/hide fields based on user selection
 */ /**
 * show/hide learn more section
 */(function(a){"use strict";a(document).on("ready",function(){var b="";a("fieldset.current-customer, fieldset.new-customer").addClass("hidden"),a("input[name=haveAccount]").on("change",function(){var c=!("yes"!==a("input[name=haveAccount]:checked").val());c?(a("fieldset.new-customer").addClass("hidden").find(":input").val(""),a("fieldset.current-customer").removeClass("hidden"),b=a("span.button-text").attr("data-updateAccount"),a("form a.button-type1").html("<span class=\"arrow-right-negative-space\">\u25B6</span> "+b)):(a("fieldset.current-customer").addClass("hidden").find(":input").val(""),a("fieldset.new-customer").removeClass("hidden"),b=a("span.button-text").attr("data-createAccount"),a("form a.button-type1").html("<span class=\"arrow-right-negative-space\">\u25B6</span> "+b))})})})(jQuery),function(a){"use strict";a(document).on("ready",function(){a(".learn-more-expanded").addClass("hidden"),a(".banner-middle").addClass("banner-middle-collapsed"),a(".circle").on("mouseenter",function(b){a(b.currentTarget).addClass("circle-hover")}).on("mouseleave",function(){a(event.currentTarget).removeClass("circle-hover")}),a(".show-more").on("click",function(){a(".learn-more-expanded").removeClass("hidden"),a(".banner-middle").removeClass("banner-middle-collapsed"),a(".learn-more-collapsed").addClass("hidden")})})}(jQuery),function(a){"use strict";// executed on mouse event
function b(b,c){a(".trigger."+c).hasClass("active")||(a(".trigger.active").removeClass("active"),a(".detail.active").hide().removeClass("active"),d=jQuery.inArray(c,e),a(".trigger."+c).addClass("active"),a(".detail."+c).fadeIn().addClass("active"))}// allows for automatically triggering activate() at the proper time
// for the next element in the sequence
function c(){var c;c=a(".banner-bottom").find(".trigger.active").attr("data-trigger"),d=3<=d?0:d+1,b(c,e[d])}var d,e;// index of active element
// order of sequence
d=0,e=["prevent-breaches","achieve-compliance","maintain-uptime","save-time-money"],a(document).on("ready",function(){var d;// kicks off the sequence
// on mouseenter, execute function activate() to hide/show content
// and stops the timed animation
// on mouseleave, restart the timed animation
d=setInterval(function(){c()},4500),a(".rollover-disabled").removeClass("rollover-disabled"),a(".banner-bottom").on("mouseenter",".trigger",function(){b(a(this).parents(".banner-bottom").find(".trigger.active").attr("data-trigger"),a(this).attr("data-trigger")),clearInterval(d)}),a(".banner-bottom").on("mouseleave",".trigger",function(){d=setInterval(function(){c()},4500)})})}(jQuery),function(a){"use strict";// executes the animation sequence cycle
// -don't run in the middle of a cycle
function b(){e&&(e=!1,a(".icon-1 .outline").transition({opacity:1,delay:500},500).transition({rotate:"+=360"},9e3,"linear").transition({opacity:0},500),a(".icon-2 .outline").transition({opacity:1,delay:1e3},500).transition({rotate:"-=359"},9e3,"linear").transition({opacity:0},500),a(".icon-3 .outline").transition({opacity:1,delay:1500},500).transition({rotate:"+=360"},9e3,"linear").transition({opacity:0},500),a(".icon-4 .outline").transition({opacity:1,delay:2e3},500).transition({rotate:"-=359"},9e3,"linear").transition({opacity:0},500),a(".icon-5 .outline").transition({opacity:1,delay:2500},500).transition({rotate:"+=360"},9e3,"linear").transition({opacity:0},500,function(){e=!0}))}// determines if the element is completely within the viewport
function c(b){var c,d,e,g;c=a(window).scrollTop(),d=c+a(window).height(),e=a(b).offset().top,g=e+a(b).height(),f=!!(e>=c&&g<=d)}var d,e,f;d=!1,e=!0,f=!1,a(document).on("scroll",function(){c(".section.intro ul"),f&&!1===d&&(d=setInterval(function(){b()},1e3)),!f&&d&&(clearInterval(d),d=!1)})}(jQuery);
//# sourceMappingURL=cm.js.map